# Generated by Django 3.1.4 on 2021-07-25 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cierre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acumulado', models.FloatField(default=0)),
                ('mes', models.PositiveIntegerField(default=None)),
                ('year', models.PositiveIntegerField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('firma', models.DateField()),
                ('year', models.PositiveIntegerField(default=0)),
                ('cup', models.FloatField(default=0)),
                ('cuc', models.FloatField(default=0)),
                ('fecha_inicio', models.DateField()),
                ('fecha_terminacion', models.DateField()),
                ('estado', models.CharField(default='', max_length=25)),
                ('clasificacion', models.CharField(default='', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformeContratacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('year', models.PositiveIntegerField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.cierre')),
            ],
        ),
        migrations.CreateModel(
            name='InformeGEIPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(default='', max_length=250)),
                ('empresa', models.CharField(default='', max_length=250)),
                ('plan_anual', models.PositiveIntegerField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(default='', max_length=250)),
                ('ejecucion', models.CharField(default='', max_length=250)),
                ('provincia', models.CharField(default='', max_length=250)),
                ('tipo', models.CharField(default='', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raudal.informecontratacion')),
            ],
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPreparacionObras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroContabilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='', max_length=250)),
                ('name', models.CharField(default='', max_length=250)),
                ('mes', models.CharField(default='', max_length=50)),
                ('autor', models.CharField(default='', max_length=250)),
                ('fecha_elaboracion', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenContratacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('empresa1', models.CharField(default='', max_length=250)),
                ('empresa2', models.CharField(default='', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenGEIPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcontrata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='', max_length=250)),
                ('mes', models.PositiveIntegerField(default=None)),
                ('year', models.PositiveIntegerField(default=None)),
                ('update_year', models.PositiveIntegerField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuplementoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='', max_length=250)),
                ('year', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntidadInversionista',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='raudal.cliente')),
            ],
            bases=('raudal.cliente',),
        ),
        migrations.CreateModel(
            name='Suplemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup', models.FloatField(default=0)),
                ('cuc', models.FloatField(default=0)),
                ('firma', models.DateField()),
                ('terminacion', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.contrato')),
                ('objeto', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.objetoobra')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(default='', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('objeto_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raudal.objetoobra')),
            ],
        ),
        migrations.AddField(
            model_name='informecontratacion',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.planpreparacionobras'),
        ),
        migrations.AddField(
            model_name='informecontratacion',
            name='resumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.resumencontratacion'),
        ),
        migrations.AddField(
            model_name='informecontratacion',
            name='resumenGEIPI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.resumengeipi'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='informe_contratacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='raudal.informecontratacion'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='informe_geipi',
            field=models.OneToOneField(null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='raudal.informegeipi'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='organismo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.organismo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='resumen_contabilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='raudal.registrocontabilidad'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='subcontrata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.subcontrata'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='supl_cont',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='raudal.suplementocontrato'),
        ),
        migrations.CreateModel(
            name='AreaEjecutora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='', max_length=250)),
                ('cup_contratado', models.FloatField(default=0)),
                ('cuc_contratado', models.FloatField(default=0)),
                ('cup_year_ant', models.FloatField(default=0)),
                ('cuc_year_ant', models.FloatField(default=0)),
                ('cup_valores_contratados_year_post', models.FloatField(default=0)),
                ('cuc_valores_contratados_year_post', models.FloatField(default=0)),
                ('cuc_ejecutado_year_ant', models.FloatField(default=0)),
                ('cup_ejecutado_year_ant', models.FloatField(default=0)),
                ('cup_ejecutado_year_actual', models.FloatField(default=0)),
                ('cuc_ejecutado_year_actual', models.FloatField(default=0)),
                ('fecha_inicio', models.DateField()),
                ('pactada_terminacion', models.DateField()),
                ('real_terminacion', models.DateField()),
                ('year', models.PositiveIntegerField(default=None)),
                ('pronostico', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.contrato')),
                ('objeto_obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.objetoobra')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='inversionista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.entidadinversionista'),
        ),
    ]
