# Generated by Django 3.1.4 on 2021-07-25 17:30

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('raudal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='informe_geipi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='raudal.informegeipi'),
        ),
    ]
