# Generated by Django 3.1.4 on 2021-08-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raudal', '0004_auto_20210725_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumengeipi',
            name='year',
            field=models.PositiveIntegerField(default=2021),
        ),
    ]
