# Generated by Django 3.1.4 on 2021-08-12 19:48

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('raudal', '0005_resumengeipi_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaejecutora',
            name='resumen',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='raudal.resumengeipi'),
        ),
    ]
