# Generated by Django 3.1.4 on 2021-08-12 19:51

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('raudal', '0006_areaejecutora_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaejecutora',
            name='resumen',
        ),
        migrations.AddField(
            model_name='contrato',
            name='no_contrato',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='resumen',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='raudal.resumengeipi'),
        ),
    ]
