# Generated by Django 3.1.4 on 2021-08-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raudal', '0007_auto_20210812_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informecontratacion',
            name='resumenGEIPI',
        ),
    ]
