# Generated by Django 3.1.4 on 2021-08-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raudal', '0009_auto_20210814_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaejecutora',
            name='objeto_obra',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.objetoobra'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='informe_contratacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='raudal.informecontratacion'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='informe_geipi',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='raudal.informegeipi'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='resumen',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='raudal.resumengeipi'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='resumen_contabilidad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='raudal.registrocontabilidad'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='supl_cont',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='raudal.suplementocontrato'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='objeto_obra',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.objetoobra'),
        ),
    ]
