# Generated by Django 3.1.4 on 2021-08-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raudal', '0010_auto_20210814_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='resumen',
            new_name='resumen_geipi',
        ),
    ]
