# Generated by Django 3.1.4 on 2021-08-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raudal', '0012_planpreparacionobras_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informecontratacion',
            name='plan',
        ),
    ]
