# Generated by Django 3.1.4 on 2021-08-18 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raudal', '0014_contrato_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeProducccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='infProduccion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='raudal.informeproducccion'),
        ),
    ]
