# Generated by Django 3.1.4 on 2021-08-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raudal', '0015_auto_20210817_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformeProducccion',
            new_name='InformeProduccion',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='infProduccion',
            new_name='inf_produccion',
        ),
    ]
