# Generated by Django 3.1.4 on 2021-08-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raudal', '0016_auto_20210817_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='orden_trabajo',
            field=models.CharField(default='', max_length=250),
        ),
    ]
