# Generated by Django 3.1.4 on 2021-08-25 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raudal', '0017_contrato_orden_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='organismo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.organismo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='subcontrata',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='raudal.subcontrata'),
        ),
    ]
