# Generated by Django 3.1.4 on 2021-08-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raudal', '0018_auto_20210824_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='suplemento',
            name='valor_actual_contratado',
            field=models.FloatField(default=0),
        ),
    ]
